config/routes.rb
Bookpiles::Application.routes.draw do
  root :to => "welcome#index"
  match '/about', :to => "welcome#about", :as => "about"

  match '/amazon/books(.:format)',    :to => "amazon#index",       :via => "get",   :as => "amazon"

  match '/logout',                    :to => "session#destroy",    :via => "get"
  match '/login',                     :to => "session#create",     :via => "post"
  match '/login-complete',            :to => "session#complete",   :via => "get",   :as => "complete_openid"

  match '/register',                  :to => "users#create",       :via => "post"

  match '/:username/books(.:format)', :to => "ownerships#index",   :via => "get",   :as => "ownerships"
  match '/:username/books',           :to => "ownerships#create",  :via => "post"

  match '/:username/books/:asin',     :to => "ownerships#update",  :via => "put",   :as => "ownership"
  match '/:username/books/:asin',     :to => "ownerships#destroy", :via => "delete"
end

app/models/ownership.rb
class Ownership < ActiveRecord::Base
  belongs_to :user
  belongs_to :book
  has_many :events

  before_save :update_moved_at

  validates_presence_of   :user, :book, :status
  validates_inclusion_of  :status,  :in => Status.all
  validates_uniqueness_of :book_id, :scope => :user_id
  validates_length_of     :notes,   :maximum => 5000

  def as_json(options=nil)
    book.as_json.merge(:status => status, :notes => notes.to_s)
  end

  private
    def update_moved_at
      self.moved_at = Time.now if status_changed?
    end
end

app/controllers/ownerships_controller.rb
class OwnershipsController < ApplicationController
  before_filter :get_user
  before_filter :check_user, :except => [:index]

  def index
    respond_to do |format|
      format.html
      format.json do
        ownerships = @user.ownerships.order("moved_at desc").includes(:book)
        render :json => ownerships.all
      end
      format.atom do
        @events = @user.events.recent.limit(params[:limit] || 20).includes(:ownership => [:book])
        @events = @events.where(:status => params[:statuses]) if params[:statuses]
        @events = @events.all
      end
    end
  end

  def create
    status, message = Services.add_book(@user, params[:asin], params[:status])
    send_message(message, status)
  end

  def update
    if params[:status]
      status, message = Services.move_book(@user, params[:asin], params[:status])
    elsif params[:notes]
      status, message = Services.add_notes_to_book(@user, params[:asin], params[:notes])
    end

    send_message(message, status)
  end

  def destroy
    status, message = Services.delete_book(@user, params[:asin])
    send_message(message, status)
  end

  private
    def get_user
      @user = User.where(:username => params[:username]).first

      if @user.nil?
        flash[:notice] = "User #{params[:username].inspect} was not found."
        redirect_to root_path
      end
    end

    def check_user
      render(:nothing => true) unless current_user == @user
    end

    def send_message(message, level=:success)
      respond_to do |format|
        message = hyperlink(message)
        format.json { render :json => {:text => message, :level => level} }
      end
    end

    def hyperlink(message)
      message.gsub(/"([^"]+)"/) do |word|
        self.class.helpers.link_to($1, ownerships_path(@user.username, :anchor => $1), :class => "pile")
      end
    end
end

app/views/ownerships/_book.html.haml
%table
  %tr
    %td= link_to(image_tag(book.image_url), ownerships_url(user.username, :anchor => status))
    %td
      %table
        %tr
          %td Title:
          %td= book.title
        %tr
          %td Authors:
          %td= book.authors
        %tr
          %td Published:
          %td= book.published_on
        %tr
          %td Pages:
          %td= book.pages
        %tr
          %td ISBN:
          %td= book.isbn

app/views/ownerships/index.html.haml
- content_for :templates do
  %script#template_book_block{:type => "text/x-jquery-tmpl"}
    %table.book_block
      %tr
        %td
          %img.book_cover{:alt => "${asin}", :src => "${image_url}", :title => "${title}"}

  %script#template_book_details{:type => "text/x-jquery-tmpl"}
    %table#book_details
      %tr
        %td.cell
          %img.book_cover{:alt => "${asin}", :src => "${image_url}", :title => "${title}"}
        %td.cell.full
          %table.details
            %tr
              %td Title:
              %td.full ${title}
            %tr
              %td Authors:
              %td ${authors}
            %tr
              %td Published:
              %td ${published_on}
            %tr
              %td Pages:
              %td ${pages}
            %tr
              %td ISBN:
              %td ${isbn}
    %ul
      %li
        %a= link_to 'View on amazon.com', "http://www.amazon.com/dp/${asin}"
      - if logged_in?
        - if current_user.username == @user.username
          %li
            Move to:
            %ul.statuses
              - Status.all.each do |status|
                %li= link_to status, "##{status}", :onclick => "backend.move_book('${asin}', '#{status}'); return false"
          %li
            = link_to "Delete", "#", :onclick => "if(confirm('delete book?')) { backend.delete_book('${asin}') }; return false"
          = form_tag "books/${asin}", :method => :put, :id => "add_notes", :onsubmit => "backend.add_notes_to_book('${asin}', $(this).find('textarea').val()); return false" do
            = text_area_tag :notes, "${notes}"
            %br
            = submit_tag "save"
        - else
          %li
            Add to:
            %ul.statuses
              - Status.all.each do |status|
                %li= link_to status, "##{status}", :onclick => "backend.add_book('${asin}', '#{status}'); return false"
      - else
        %pre.notes ${notes}

- content_for :head do
  = auto_discovery_link_tag(:atom, ownerships_url(@user.username, :format => 'atom'), :title => "#{@user.username}'s books")

- content_for :header do
  #controls.span-24
    %ul.statuses
      - Status.all.each do |status|
        %li{:class => "status_#{status} tab"}
          = link_to(status, ownerships_path(@user.username, :anchor => status), :class => "pile")
          %span.count
    .search
      %input{:type => "search", :results => "results", :placeholder => "Filter", :size => 30}
    - if current_user == @user
      .actions
        = link_to "add a book", amazon_path, :id => "amazon_search"

- content_for :page_js do
  = javascript_include_tag "bookpiles.js"
  = javascript_include_tag "ownerships.js"
  = javascript_tag do
    - if current_user
      != "backend.init(#{current_user.username.inspect}, function() { controller.update_books(); });"