config/routes.rb
Bookpiles::Application.routes.draw do
  root :to => "welcome#index"
  match '/about', :to => "welcome#about", :as => "about"

  match '/amazon/books(.:format)',    :to => "amazon#index",       :via => "get",   :as => "amazon"

  match '/logout',                    :to => "session#destroy",    :via => "get"
  match '/login',                     :to => "session#create",     :via => "post"
  match '/login-complete',            :to => "session#complete",   :via => "get",   :as => "complete_openid"

  match '/register',                  :to => "users#create",       :via => "post"

  match '/:username/books(.:format)', :to => "ownerships#index",   :via => "get",   :as => "ownerships"
  match '/:username/books',           :to => "ownerships#create",  :via => "post"

  match '/:username/books/:asin',     :to => "ownerships#update",  :via => "put",   :as => "ownership"
  match '/:username/books/:asin',     :to => "ownerships#destroy", :via => "delete"
end

app/views/layouts/application.html.haml
<!DOCTYPE HTML>
%html
  %head
    <meta charset="utf-8" />
    %title bookpiles
    = stylesheet_link_tag 'screen.css', '/facebox/facebox.css', 'master.css', :cache => 'app', :media => 'all'
    = stylesheet_link_tag 'print.css', :media => 'print'
    = csrf_meta_tag
    = yield :head
  %body

    #header
      .wrapper
        = link_to 'bookpiles', root_path, :id => 'logo'

        .logister_links
          - if logged_in?
            = link_to current_user.username, ownerships_path(current_user.username)
            |
            = link_to "logout", logout_path
          - else
            = link_to "register", "#register_form", :rel => "facebox"
            |
            = link_to "login", "#login_form", :rel => "facebox"

        #loader.hide
          = image_tag "small-ajax-loader.gif"

        #flash{:class => flash.keys.first}
          = flash.values.first

        = yield :header

    .container
      #content.span-24
        = yield

    .templates.hide
      #login_form
        .small_popup
          = form_tag "/login" do
            %div
              = label_tag "username", "Username:"
            %div
              = text_field_tag "username"
            .submit
              = submit_tag "login", :name => nil
      #register_form
        .small_popup
          = form_tag "/register" do
            %div
              = label_tag "username", "Username:"
            %div
              = text_field_tag "username"
              %p.description
                This is the username you would like to use on bookpiles.
            %div
              = label_tag "openid", "OpenID:"
              = link_to "What is OpenID?", "http://openid.net/get-an-openid/what-is-openid/", :style => "font-weight: normal; font-size: 80%; margin-left: 10px"
            %div
              = text_field_tag "openid", '', :style => "width: 350px"
              %p.description
                This is your OpenID URL. In many cases, the domain (e.g. myopenid.com, yahoo.com) is sufficient.
            .submit
              = submit_tag "register", :name => nil
      = yield :templates

    = javascript_include_tag 'jquery-1.5.min.js','/facebox/facebox.js','jquery.tmpl.min.js','pipes.js','application.js', :cache => 'app'
    = yield(:page_js)